from decimal import Decimal

# General defaults
DEFAULT_MONTHLY_INCOME = Decimal("75000.00")

# Financial Health & Diagnostic Scores
DEFAULT_DEBT_SCORE = 70
HEALTH_SAVINGS_WEIGHT = 0.35
HEALTH_BUDGET_WEIGHT = 0.25
HEALTH_INVESTMENT_WEIGHT = 0.25
HEALTH_DEBT_WEIGHT = 0.15

INVESTMENT_SCORE_ACTIVE = 82
INVESTMENT_SCORE_INACTIVE = 50

# Emergency Runway & Reserves
EMERGENCY_RUNWAY_HEALTHY_MONTHS = 3.0
EMERGENCY_RUNWAY_FALLBACK = 6.0

# Spending & Budgeting benchmarks
WANTS_PCT_THRESHOLD = 35.0
SAVINGS_PCT_THRESHOLD = 20.0

FOOD_OPTIMIZATION_INCOME_PCT = 0.15
FOOD_OPTIMIZATION_SAVINGS = Decimal("3200.00")

BUDGET_OVERRUN_TRIM_FACTOR = 0.9

FOOD_BUDGET_THRESHOLD_PCT = Decimal("0.12")
FOOD_BUDGET_RECOMMENDED_PCT = Decimal("0.10")

SHOPPING_BUDGET_THRESHOLD_PCT = Decimal("0.08")
SHOPPING_BUDGET_RECOMMENDED_PCT = Decimal("0.06")

RECOMMENDED_BUDGET_FALLBACK_INCOME_PCT = Decimal("0.55")

# Investments
DIVERSIFICATION_SCORE_CAP = 10.0
DIVERSIFICATION_TYPE_MULTIPLIER = 2.0
EQUITY_CONCENTRATION_THRESHOLD_PCT = 60.0

DEFAULT_PORTFOLIO_BETAS = {
    "Stocks": 1.2,
    "Mutual Funds": 1.0,
    "ETFs": 0.9,
    "Bonds": 0.1,
    "Other": 0.5,
    "Other Investments": 0.5
}

# Portfolio target allocations based on risk preference
EQUITY_TARGETS_BY_RISK = {
    "AGGRESSIVE": 75.0,
    "CONSERVATIVE": 40.0,
    "MODERATE": 60.0
}
EQUITY_TARGET_BUFFER_PCT = 15.0

# Tax Regime Constants
INDIA_TAX_STD_DEDUCTION_NEW = Decimal("75000.00")
INDIA_TAX_STD_DEDUCTION_OLD = Decimal("50000.00")
